name: CI - OSX/Linux via Conda

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'scripts/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'doc/'
      - 'scripts/'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'

jobs:
  qrw-conda:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }} ${{ matrix.build_type }} ${{ matrix.cxx_options }}
    runs-on: ${{ matrix.os }}
    env:
      CCACHE_BASEDIR: "${GITHUB_WORKSPACE}"
      CCACHE_DIR: "${GITHUB_WORKSPACE}/.ccache"
      CCACHE_COMPRESS: true
      CCACHE_COMPRESSLEVEL: 6

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        build_type: [Release]
        python-version: ["3.10", "3.12"]
        cxx_options: ["", "-mavx2"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/cache@v4
      with:
        path: .ccache
        key: ccache-macos-linux-conda-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.python-version }}-${{ matrix.cxx_options }}-${{ github.sha }}
        restore-keys: ccache-macos-linux-conda-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.python-version }}-

    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: qrw
        auto-update-conda: true
        environment-file: .github/workflows/conda/environment_macos_linux.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Build qrw
      shell: bash -el {0}
      run: |
        conda list
        echo $CONDA_PREFIX

        mkdir build
        cd build

        cmake .. \
          -GNinja \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DPYTHON_EXECUTABLE=$(which python3) \
          -DBUILD_PYTHON_INTERFACE=ON \
          -DGENERATE_PYTHON_STUBS=ON
        cmake --build .
        ctest --output-on-failure
        cmake --install .

    - name: Uninstall qrw
      shell: bash -el {0}
      run: |
        cd build
        cmake --build . --target uninstall

  check:
    if: always()
    name: check-macos-linux-conda

    needs:
    - qrw-conda

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
